### ISSUE TITLE
Wyszukiwanie terminów telefonicznych zdaje się nie działać

### ISSUE THREAD

**Issue by RobusK** [pawliczka/LuxmedSniper#30]
Przy ustawieniu:

```
luxmedsniper:
  doctor_locator_id: -1*13410*-1*-1 # (cityId, serviceVariantId, facilitiesIds, doctorsIds) -1 means any.
                                  # You can get those ids by reading form data sent to https://portalpacjenta.luxmed.pl/PatientPortal/Reservations/Reservation/PartialSearch
                                  # on https://portalpacjenta.luxmed.pl/PatientPortal/Reservations/Reservation/Search by Chrome dev tools
  lookup_time_days: 3 # How many days from now should script look at.
```

nie znajduje żadnych terminów konsultacji telefonicznej z internistą, choć na stronie widać wolne terminy za 3 dni. Próbowałem również z ustawionym cityId - efekt ten sam. Luxmed teraz wyszukuje konsultacje telefoniczne w całej Polsce -może coś się zmieniło w API?

[edit]

Po krótkim researchu, wygląda na to, że portal pacjenta bierze terminy stąd:
`https://portalpacjenta.luxmed.pl/PatientPortal/NewPortal/terms/oneDayTerms?cityId=*redacted*&serviceVariantId=13410&languageId=10&searchDateFrom=2023-11-16&searchDateTo=2023-11-16&processId=*redacted*&searchByMedicalSpecialist=false&expectedTermsNumber=*redacted*&delocalized=false`
